# Generated by Django 3.2.24 on 2025-01-26 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pdf_processor', '0002_alter_pdfdocument_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pdfdocument',
            name='embeddings',
            field=models.BinaryField(null=True),
        ),
    ]
