# Generated by Django 3.2.24 on 2025-01-28 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pdf_processor', '0003_make_embeddings_nullable'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pdfdocument',
            name='content',
            field=models.TextField(blank=True),
        ),
    ]
