# Generated by Django 3.2.24 on 2025-01-28 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pdf_processor', '0004_alter_pdfdocument_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='pdfdocument',
            name='is_indexed',
            field=models.BooleanField(default=False),
        ),
    ]
