# Generated by Django 3.1.12 on 2024-12-21 18:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Route',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parent_path', models.CharField(blank=True, max_length=255, null=True)),
                ('title', models.CharField(max_length=255)),
                ('path', models.CharField(max_length=255, unique=True)),
                ('view', models.CharField(max_length=255)),
                ('image', models.CharField(blank=True, max_length=255, null=True)),
                ('file', models.CharField(blank=True, max_length=255, null=True)),
                ('expire_date', models.CharField(blank=True, max_length=255, null=True)),
                ('date', models.DateTimeField()),
                ('details', models.TextField(blank=True, null=True)),
                ('data', models.JSONField(blank=True, null=True)),
            ],
            options={
                'db_table': 'routes',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userName', models.CharField(max_length=255, unique=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(max_length=255)),
                ('active', models.BooleanField(default=True)),
                ('admin', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'users',
            },
        ),
        migrations.CreateModel(
            name='GroopRoute',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('permission', models.CharField(choices=[('Download', 'Download'), ('NoDownload', 'NoDownload')], max_length=20)),
                ('route', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pdf_app.route')),
            ],
        ),
        migrations.CreateModel(
            name='Groop',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('groop_name', models.CharField(max_length=255, unique=True)),
                ('groop_routes', models.ManyToManyField(blank=True, to='pdf_app.GroopRoute')),
                ('groop_users', models.ManyToManyField(to='pdf_app.User')),
            ],
            options={
                'db_table': 'groops',
            },
        ),
    ]
