# Generated by Django 5.1.4 on 2024-12-23 09:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pdf_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='groop',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='route',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'managed': False},
        ),
    ]
